### ISSUE TITLE
Create Chat Section

### ISSUE THREAD

**Issue by pjsherpa** [iamjoyfulgirl/barcade#19]

**Comment by cassandrakise** [comment]
Ordinary Coders // specifically for react and chakra -- [https://ordinarycoders.com/blog/article/react-chakra-ui](url)
TalkJS -- [https://talkjs.com/docs/Getting_Started/](url)
React Open Source Chat Function example  -- [https://reactjsexample.com/the-react-project-for-the-open-source-chat-platform/](url)
Chitchatter (serverless though) -- [https://reactjsexample.com/a-peer-to-peer-chat-app-that-is-serverless-decentralized-and-ephemeral/](url)

**Comment by cassandrakise** [comment]
done
